# For apps, the maximal range is 0:5000 for both train and test
[apps]
active = true
test_start_index = 0
test_end_index = 2
train_start_index = 0
train_end_index = 2

# For mbpp, the maximal range is 0:47
[mbpp]
active = true
test_len = 2
train_len = 2

[gptme]
active = true
